### ISSUE TITLE
README associated with Raider dataset

### ISSUE THREAD

**Issue by bam54** [cameronphchen/SRM#1]
Hello,

The README given in SRM-master/data/input/raider/500vx/2203TR doesn't seem to correspond to the data in this folder.  Specifically, the names of the files being described are not contained in this folder and the files that are contained, are not described.  Could you please provide an updated README that describes the files given?

Thanks,
Brian

**Comment by cameronphchen** [comment]
Thanks for pointing this out! I have updated the readme. Please feel free to follow up if you have any other questions.
